title: Yash Mali - Machine Learning Researcher & AI Developer | UBC Computer Science Student Vancouver
description: UBC Computer Science student specializing in ML/AI research, neural networks, deep learning. Experience in healthcare AI, optimization, NLP at Vancouver.
